### ISSUE TITLE
Difficult in generating partial point clouds

### ISSUE THREAD

**Issue by HezhiCao** [wentaoyuan/it-net#1]
Hi, happy new year!

I have trouble in generating the partial data. Can you give a more detailed example when running `python parallel_render.py [model list] [intrinsics file] [output directory]`
what should  `[model list] [intrinsics file] [output directory]` be?

Besides, when I set  `[intrinsics file]` to `modelnet40_manually_aligned/airplane/train/airplane_0001.off`, it can not be read by `intrinsics = np.loadtxt(intrinsics_file,skiprows=True)` in `render_single.py(line 54)` because its column number is different. 
`ValueError: Wrong number of columns at line 90717`

Moreover, `scene, camera, output = setup_blender(width, height, focal)` will give an error 
`AttributeError: 'RenderSettings' object has no attribute 'alpha_mode'` 

Hope you can give a more detailed example. @wentaoyuan
Thanks!

**Comment by wentaoyuan** [comment]
`[model list]` should be a `.txt` file, where each line has the format `airplane_0001`. See `test_models.txt` for an example.

`[intrinsics file]` should be a `.txt` file containing the 3x3 camera intrinsics matrix. I've uploaded an example under `prepare_data`.
